ci:
    autofix_commit_msg: |
        ci: auto fixes from pre-commit hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: ^.*\b(alembic|\.idea)\b.*$
      - id: end-of-file-fixer
        exclude: ^.*\b(alembic|\.idea)\b.*$
      - id: trailing-whitespace
        exclude: ^.*\b(alembic|\.idea)\b.*$
      - id: check-merge-conflict
        exclude: ^.*\b(alembic|\.idea)\b.*$
      - id: detect-private-key
        exclude: ^.*\b(alembic|\.idea)\b.*$
      - id: debug-statements
        exclude: ^.*\b(alembic|\.idea)\b.*$

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^.*\b(alembic|\.idea)\b.*$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^.*\b(.idea)\b.*$
      # Run the formatter.
      - id: ruff-format
        exclude: ^.*\b(.idea)\b.*$

#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.5.0
#    hooks:
#    -   id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']
#        exclude: package.lock.json
